name: Pull request

on:
  pull_request:

jobs:
  verify-and-scan-11:
    permissions:
      security-events: write
    uses: ./.github/workflows/wf_verifyandscan.yaml
    with:
      zulu_version: "zulu11.90.205-ca-jre11.0.32"

  verify-and-scan-17:
    permissions:
      security-events: write  
    uses: ./.github/workflows/wf_verifyandscan.yaml
    with:
      zulu_version: "zulu17.68.203-ca-jdk17.0.20"

  verify-and-scan-21:
    permissions:
      security-events: write  
    uses: ./.github/workflows/wf_verifyandscan.yaml
    with:
      zulu_version: "zulu21.52.203-ca-jdk21.0.12"

  verify-and-scan-25:
    permissions:
      security-events: write  
    uses: ./.github/workflows/wf_verifyandscan.yaml
    with:
      zulu_version: "zulu25.36.205-ca-jdk25.0.4"