name: Pull request

on:
  pull_request:

jobs:
  verify-and-scan-11:
    permissions:
      security-events: write
    uses: ./.github/workflows/wf_verifyandscan.yaml
    with:
      zulu_version: "zulu11.62.17-ca-jre11.0.18"

  verify-and-scan-17:
    permissions:
      security-events: write  
    uses: ./.github/workflows/wf_verifyandscan.yaml
    with:
      zulu_version: "zulu17.40.19-ca-jdk17.0.6"
