on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * 1"
    - cron: "30 1 * * 1"

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: setdefaultenv17
        run: |
          echo "tagversion=17" >> $GITHUB_ENV
          echo "javaversion=zulu17.40.19-ca-jdk17.0.6" >> $GITHUB_ENV        
      - name: setenv11
        if: github.event.schedule=='0 1 * * 1'
        run: |
          echo "tagversion=11" >> $GITHUB_ENV
          echo "javaversion=zulu11.62.17-ca-jre11.0.18" >> $GITHUB_ENV
      - name: setenv17
        if: github.event.schedule=='30 1 * * 1'
        run: |
          echo "tagversio=17" >> $GITHUB_ENV
          echo "javaversion=zulu17.40.19-ca-jdk17.0.6" >> $GITHUB_ENV
      - uses: actions/checkout@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1      
      - name: Login to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: groundhog2k/distroless-azul-jre:${{ env.tagversion }}
          build-args: |
            ZULU_VERSION=${{ env.javaversion }}
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
