on:
  push:
    branches:
      - main

jobs:
  build-and-push-11:
    secrets: inherit
    uses: ./.github/workflows/zulu11.yaml

  build-and-push-17:
    secrets: inherit
    uses: ./.github/workflows/zulu17.yaml

  build-and-push-21:
    secrets: inherit
    uses: ./.github/workflows/zulu21.yaml
