on: [pull_request]

jobs:
  verify-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set environment variables
        run: |
          source ./version.cfg
      - run: docker build . -t groundhog2k/distroless-azul-jre:verify --build-args ZULU_VERSION=$ZULU_VERSION --build-args DEBIAN_VERSION=$DEBIAN_VERSION
      - uses: Azure/container-scan@v0
        with:
          image-name: groundhog2k/distroless-azul-jre:verify
