on: [pull_request]

jobs:
  verify-image:
    runs-on: ubuntu-latest
    steps:
      - name: initenv
        run: echo "javaversion=zulu17.40.19-ca-jdk17.0.6" >> $GITHUB_ENV
      - name: checkitout
        uses: actions/checkout@master
      - name: build
        run: docker build . -t groundhog2k/distroless-azul-jre:verify --build-arg ZULU_BASE_VERSION=${{ env.javaversion }}
      - name: Scan image with trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'groundhog2k/distroless-azul-jre:verify'
          format: 'table'
          ignore-unfixed: true
      - name: Scan image with grype
        uses: anchore/scan-action@v3
        id: scangrype
        with:
          image: "groundhog2k/distroless-azul-jre:verify"
          severity-cutoff: "low"
          fail-build: false
          acs-report-enable: true
      - name: Inspect action SARIF report
        run: cat ${{ steps.scangrype.outputs.sarif }}
      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.scangrype.outputs.sarif }}
