on: [pull_request]

jobs:
  verify-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: docker build . -t groundhog2k/distroless-azul-jre:verify
      - name: Scan image with trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'groundhog2k/distroless-azul-jre:verify'
          format: 'table'
          ignore-unfixed: true
      - name: Scan image with anchore grype
        uses: anchore/scan-action@v3
        with:
          image: "groundhog2k/distroless-azul-jre:verify"
