on: [pull_request]

jobs:
  verify-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set environment variables
        run: |
          source ./version.cfg
          export ZULU_VERSION DEBIAN_VERSION
      - name: Build image
        run: docker build . -t groundhog2k/distroless-azul-jre:verify --build-arg ZULU_VERSION=$ZULU_VERSION --build-arg DEBIAN_VERSION=$DEBIAN_VERSION
      - name: Scan image
        uses: Azure/container-scan@v0
        with:
          image-name: groundhog2k/distroless-azul-jre:verify
