name: Azul Zulu JRE 17
on:
  workflow_call:

jobs:
  build-and-push-17:
    secrets: inherit
    uses: ./.github/workflows/wf_buildandpush.yaml
    with:
      zulu_version: "zulu17.46.19-ca-jdk17.0.9"
      tags: "groundhog2k/distroless-azul-jre:17, groundhog2k/distroless-azul-jre:17.0.9"
